import {
	BYSTANDERS,
	HENCHMEN_GROUPS,
	HEROES,
	MASTER_STRIKE,
	VILLAIN_GROUPS
} from './index';

export const PlayerRequirements = {
	1: {
		[HEROES]: 3,
		[VILLAIN_GROUPS]: 1,
		[HENCHMEN_GROUPS]: 1,
		[BYSTANDERS]: 1,
		[MASTER_STRIKE]: 1
	},
	2: {
		[HEROES]: 5,
		[VILLAIN_GROUPS]: 2,
		[HENCHMEN_GROUPS]: 1,
		[BYSTANDERS]: 2,
		[MASTER_STRIKE]: 5
	},
	3: {
		[HEROES]: 5,
		[VILLAIN_GROUPS]: 3,
		[HENCHMEN_GROUPS]: 1,
		[BYSTANDERS]: 8,
		[MASTER_STRIKE]: 5
	},
	4: {
		[HEROES]: 5,
		[VILLAIN_GROUPS]: 3,
		[HENCHMEN_GROUPS]: 2,
		[BYSTANDERS]: 8,
		[MASTER_STRIKE]: 5
	},
	5: {
		[HEROES]: 6,
		[VILLAIN_GROUPS]: 4,
		[HENCHMEN_GROUPS]: 2,
		[BYSTANDERS]: 12,
		[MASTER_STRIKE]: 5
	}
};
